version:  '3'
services:
  datascience-notebook:
      build:
        context: './docker-build-context/'
      restart: unless-stopped
      container_name:   jupyterlab
      volumes:
        - ${LOCAL_WORKING_DIR}:/home/jovyan/work:Z
        - ${LOCAL_DATASETS}:/home/jovyan/datasets:Z
      ports:
        - ${BIND_HOST}:${PORT}:8888
      networks:
        - jupyter
      dns:
        - 1.1.1.1
        - 1.0.0.1
      command: "start-notebook.sh \
        --ServerApp.password=${ACCESS_TOKEN} \
        --ServerApp.base_url=/ \
        --ServerApp.allow_origin=* \
        --ServerApp.trust_xheaders=True \
        --ServerApp.allow_remote_access=True \
        --ServerApp.quit_button=False"
      healthcheck:
        test: curl --fail http://localhost:8888 || exit 1
        interval: 60s
        retries: 5
        start_period: 180s
        timeout: 12s
networks:
  jupyter:
    driver: bridge
    #driver_opts:
    #  com.docker.network.bridge.enable_ip_masquerade: 'false'
    ipam:
      driver: default
      config:
       -
        subnet: 172.18.80.0/24
        gateway: 172.18.80.1
        